services:
  ftp_server:
    image: stilliard/pure-ftpd
    container_name: ftp_server
    volumes:
      - ./ftp:/home/ftpusers
    environment:
      FTP_USER_NAME: "ftpuser"
      FTP_USER_PASS: "ftppass"
      FTP_USER_HOME: "/home/ftpusers/ftpuser"
      FTP_PASSIVE_PORTS: "30000:30009"
      FTP_UID: "1000"
      FTP_GID: "1000"
    restart: always
    hostname: ftp_server
    # networks:
    #   inquisitor_network:
    #     ipv4_address: 192.168.0.254

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    command: ["sleep", "5000"]
    depends_on:
      - ftp_server
    restart: always
    hostname: client
    # networks:
    #   inquisitor_network:
    #     ipv4_address: 192.168.0.253

  inquisitor:
    build:
      context: ./inquisitor
      dockerfile: Dockerfile
    container_name: inquisitor
    volumes:
      - ./inquisitor:/inquisitor
    command: ["sleep", "5000"]
    depends_on:
      - ftp_server
      - client
    restart: always
    hostname: inquisitor
    # networks:
    #   inquisitor_network:
    #     ipv4_address: 192.168.0.252

# networks:
#   inquisitor_network:
#     name: inquisitor_network
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 192.168.0.0/24

