services:
  ftp_server:
    build:
      context: ./ftp_server
      dockerfile: Dockerfile
    image: inquisitor/ftp_server
    container_name: ftp_server
    volumes:
      - ./inquisitor:/inquisitor
    working_dir: /inquisitor
    environment:
      FTP_USER: lockdoor
      FTP_PASS: password
    restart: always
    hostname: inquisitor
    networks:
      inquisitor:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: inquisitor/client
    container_name: client
    volumes:
      - ./inquisitor:/inquisitor
    working_dir: /inquisitor
    command: ["sleep", "infinity"]
    restart: always
    hostname: client
    networks:
      inquisitor:

  inquisitor:
    build:
      context: ./inquisitor
      dockerfile: Dockerfile
    container_name: inquisitor
    image: inquisitor/inquisitor
    volumes:
      - ./inquisitor:/inquisitor
    command: ["sleep", "infinity"]
    restart: always
    hostname: inquisitor
    networks:
      inquisitor:

networks:
  inquisitor:
    name: inquisitor
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 192.168.0.0/24



